pipeline {
    agent any

    environment { PROJECT_DIR = 'frontend' }

    tools {
        nodejs 'node-20'
    }

    environment {
        BUILD_DIR = 'out'

        FTP_HOST = 'ftp.mbl1.by'
        FTP_USER = 'mbl1_ftp@dev.mbl1.by'
        FTP_PASS = 'oCPJzA{$fW{U'   // ⚠️ потом уберём в credentials
        REMOTE_PATH = 'public_html/dev/' // уточни путь!
        
        NEXT_PUBLIC_CLIENT_API_URL = 'https://api.mbl1.by'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install') {
            steps {
                sh 'npm ci'
            }
        }

        stage('Build (SSG)') {
            steps {
                sh 'npm run build'
            }
        }

        stage('Check build') {
            steps {
                sh 'ls -la out'
            }
        }

        stage('Deploy via FTP') {
            steps {
                sh '''
                apt-get update -y
                apt-get install -y lftp

                lftp -u $FTP_USER,$FTP_PASS $FTP_HOST <<EOF
                set ftp:ssl-allow no
                mirror -R --delete $BUILD_DIR $REMOTE_PATH
                quit
EOF
                '''
            }
        }
    }

    post {
        success {
            echo '🚀 Deploy SUCCESS'
        }
        failure {
            echo '💥 Deploy FAILED'
        }
    }
}
