pipeline {
    agent any

    tools {
        nodejs 'node-22'
    }

    environment {
        NEXT_PUBLIC_CLIENT_API_URL='https://api.mbl1.by'

        API_TOKEN=GbOjzxPfosOPItS_v28R-DYNyFR5kBN7
        
        PROJECT_DIR = 'frontend'
        BUILD_DIR = 'out'

        FTP_HOST = 'dev.mbl1.by'
        REMOTE_PATH = 'public_html/dev/'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install') {
            steps {
                dir(PROJECT_DIR) {
                    sh 'npm ci'
                }
            }
        }

        stage('Build (SSG)') {
            steps {
                dir(PROJECT_DIR) {
                    sh 'npm run build'
                }
            }
        }

        stage('Check build') {
            steps {
                dir(PROJECT_DIR) {
                    sh 'ls -la out'
                }
            }
        }

        stage('Deploy via FTP') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'ftp-cred',
                    usernameVariable: 'FTP_USER',
                    passwordVariable: 'FTP_PASS'
                )]) {
                    sh '''
                    # Устанавливаем lftp, если его нет
                    which lftp || (apt-get update -y && apt-get install -y lftp)

                    lftp -u $FTP_USER,$FTP_PASS $FTP_HOST <<EOF
                    set ftp:ssl-allow no
                    mirror -R --delete --only-newer $PROJECT_DIR/$BUILD_DIR/ $REMOTE_PATH
                    quit
EOF
                    '''
                }
            }
        }
    }

    post {
        success {
            echo '🚀 Deploy SUCCESS'
        }
        failure {
            echo '💥 Deploy FAILED'
        }
    }
}
