pipeline {
    agent any

    tools {
        nodejs 'node-20'
    }

    environment {
        PROJECT_DIR = 'frontend'
        BUILD_DIR = 'out'

        FTP_HOST = '93.125.99.44'
        FTP_USER = '54cda2d1@mbl1.by'
        FTP_PASS = 'uBh?av&ex7n!'
        REMOTE_PATH = 'public_html/dev/'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install') {
            steps {
                dir('frontend') {
                    sh 'npm ci'
                }
            }
        }

        stage('Build (SSG)') {
            steps {
                dir('frontend') {
                    sh 'npm run build'
                }
            }
        }

        stage('Check build') {
            steps {
                dir('frontend') {
                    sh 'ls -la out'
                }
            }
        }

        stage('Deploy via FTP') {
            steps {
                sh '''
                apt-get update -y
                apt-get install -y lftp

                lftp -u $FTP_USER,$FTP_PASS $FTP_HOST <<EOF
                set ftp:ssl-allow no
                mirror -R --delete $PROJECT_DIR/$BUILD_DIR $REMOTE_PATH
                quit
EOF
                '''
            }
        }
    }

    post {
        success {
            echo '🚀 Deploy SUCCESS'
        }
        failure {
            echo '💥 Deploy FAILED'
        }
    }
}
