export const dynamic = 'force-static';

import Footer from '_components/Footer';
import Header from '_components/Header';
import AppProvider from '_context/AppProvider';
import { BreadcrumbsProvider } from '_context/BreadcrumbsProvider';
import type { Metadata } from 'next';
import { Inter, Manrope } from 'next/font/google';
import './globals.css';

const inter = Inter({
  subsets: ['latin', 'cyrillic'],
  variable: '--font-sans',
  display: 'swap',
});

const manrope = Manrope({
  subsets: ['latin', 'cyrillic'],
  variable: '--font-heading',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className={`${inter.variable} ${manrope.variable}`}>
      <body className="antialiased">
        <AppProvider>
          <Header />
          <a
            href="#main-content"
            className="sr-only focus:not-sr-only p-2 bg-primary text-white rounded z-50 fixed top-2 left-2"
          >
            Перейти к основному контенту
          </a>
          <main id="main-content" className="min-h-screen mt-16 md:mt-24 lg:mt-16">
            <BreadcrumbsProvider>{children}</BreadcrumbsProvider>
          </main>
          <Footer />
        </AppProvider>
      </body>
    </html>
  );
}
