import AppProvider from '_context/AppProvider';
import type { Metadata } from 'next';
import { Inter, Playfair_Display } from 'next/font/google';
import Header from '../components/Header';
import './globals.css';

const inter = Inter({
  subsets: ['latin', 'cyrillic'],
  variable: '--font-sans',
  display: 'swap',
});

const playfair = Playfair_Display({
  subsets: ['latin', 'cyrillic'],
  variable: '--font-serif',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className={`${inter.variable} ${playfair.variable}`}>
      <body className="antialiased">
        <AppProvider>
          <Header />
          <a
            href="#main-content"
            className="sr-only focus:not-sr-only p-2 bg-primary text-white rounded z-50 fixed top-2 left-2"
          >
            Перейти к основному контенту
          </a>
          <main id="main-content" className="mt-[8rem] mx-4 md:mx-6 lg:mx-12 xl:mx-32 2xl:mx-64">
            {children}
          </main>
        </AppProvider>
      </body>
    </html>
  );
}
